export let defaultData = [
				{
					id: 1,
					name: 'Quattro formaggi',
					category: 'pizza',
					size: '32cm',
					photo: 'pizza1.png',
					compound: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
					price: 119,
					hit: true,
				},
				{
					id: 2,
					name: 'Карбонара',
					category: 'pizza',
					size: '32cm',
					photo: 'pizza2.png',
					compound: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
					price: 119,
					hit: true,
				},
				{
					id: 3,
					name: 'Філадельфія селмон',
					category: 'pizza',
					size: '32cm',
					photo: 'pizza3.png',
					compound: 'Dough, mozzarella, barrel, eggs, Parmesan cheese',
					price: 129,
					hit: false,
				},
				{
					id: 4,
					name: 'Ді маре',
					category: 'pizza',
					size: '32cm',
					photo: 'pizza4.png',
					compound: 'Dough, mozzarella, barrel, eggs, Parmesan cheese',
					price: 139,
					hit: false,
				},
				{
					id: 5,
					name: 'Кватро формаджіо',
					category: 'pizza',
					size: '32cm',
					photo: 'pizza5.png',
					compound: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
					price: 129,
					hit: false,
				},
				{
					id: 6,
					name: 'Кватро формаджіо',
					category: 'pizza',
					size: '32cm',
					photo: 'pizza6.png',
					compound: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
					price: 129,
					hit: false,
				},
				{
					id: 7,
					name: 'Кватро формаджіо',
					category: 'pizza',
					size: '32cm',
					photo: 'pizza7.png',
					compound: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
					price: 129,
					hit: false,
				},
				{
					id: 8,
					name: 'Кватро формаджіо',
					category: 'pizza',
					size: '32cm',
					photo: 'pizza8.png',
					compound: 'Dough, Mozzarella, Cheddar, Blue, Parmesan',
					price: 129,
					hit: false,
				},
				{
					id: 9,
					name: 'Pepsi',
					category: 'drink',
					size: '0.3',
					photo: 'pepsi.png',
					compound: '',
					price: 20,
					hit: true,
				},
				{
					id: 10,
					name: 'Coca Cola',
					category: 'drink',
					size: '0.3',
					photo: 'cola.png',
					compound: '',
					price: 20,
					hit: false,
				},
				{
					id: 11,
					name: 'Fanta',
					category: 'drink',
					size: '0.3',
					photo: 'fanta.png',
					compound: '',
					price: 20,
					hit: false,
				},
			]